# Generated by Django 5.0.4 on 2024-04-11 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_speciality_user_speciality_delete_doctor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name': 'Специализация', 'verbose_name_plural': 'Специализации'},
        ),
    ]
