# Generated by Django 5.0.4 on 2024-04-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_speciality_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.speciality', verbose_name='Специализация'),
        ),
    ]
