# Generated by Django 5.0.4 on 2024-04-11 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='speciality',
        ),
        migrations.AddField(
            model_name='speciality',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Доктора'),
        ),
    ]
