# Generated by Django 5.0.4 on 2024-04-11 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_speciality_speciality_doctors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='doctors',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Имя')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user/doctor', verbose_name='фото')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.speciality')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
    ]
