# Generated by Django 5.0.4 on 2024-04-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='services',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
