# Generated by Django 5.0.4 on 2024-04-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smo', '0003_blogwriter_delete_news_alter_services_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='services/icons/', verbose_name='Иконка'),
        ),
    ]
