# Generated by Django 5.0.4 on 2024-04-11 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smo', '0006_services_doctor'),
        ('users', '0005_alter_user_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='doctor',
        ),
        migrations.AddField(
            model_name='services',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.speciality'),
        ),
    ]
