# Generated by Django 5.0.4 on 2024-04-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smo', '0009_blogwriter_owner'),
        ('users', '0007_remove_speciality_doctors_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwriter',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
    ]
