# Generated by Django 5.0.4 on 2024-04-20 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smo', '0010_alter_blogwriter_owner'),
        ('users', '0007_remove_speciality_doctors_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, max_length=35, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('date', models.DateField(verbose_name='Дата')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Доктор')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.speciality', verbose_name='Специализация')),
            ],
        ),
    ]
